### ISSUE TITLE
Internal server error when copying and saving checklists from another week or course

### ISSUE THREAD

**Issue by Mamelukki** [UniversityOfHelsinkiCS/labtool#1060] opened 2019-12-09 11:52 UTC
Copying an existing checklist from another week or course and saving it causes an internal server error

**Comment by hisahi** [comment] 2019-12-09 14:22
This seemingly only affects the test data and is likely caused by either a bug in Sequelize or postgres with auto-increment of IDs not working correctly, causing conflicts whenever any new items are added, which lead to primary key constraint failures, which lead to the error discussed here

**Comment by hisahi** [comment] 2019-12-10 12:39
Fixed in #1059

**Closed by hisahi** 2019-12-10 12:39 UTC
Labels: backend, bug
